version: 3

services:
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - microcontroller-microservice-database:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432

volumes:
  microcontroller-microservice-database:
    extenal: false